apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-wasm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-wasm
  template:
    metadata:
      labels:
        app: test-wasm
    spec:
      runtimeClassName: wasmedge
      containers:
        - name: wasmtest
          image: ttl.sh/wasmtest:1d

